export const daoData = [{
		"category": "[\"Investment\",\"DeFi\"]",
		"name": "MeanFi",
		"daoToken": "MEAN",
		"Token address": "MEANeD3XDdUmNMsRGjASkSWdC8prLYsoRJ61pPeHctD",
		"Treasury Address": "GNHnU2infXYKu1HvDfNWrpNFNwz8CubrudVNgTZz8LSf",
		"verified": "checked",
		"chain": "SOL",
		"description": "MeanFi is a censorship-resistant, user-friendly, self-custody, permissionless & trustless bank bringing everyday banking workflows and real-time finance to crypto and DeFi.\n\nPeople and businesses from around the world can create and manage international accounts with thousands of assets like stables coins and tokens, as well as access several capital products like deep liquidity markets, a decentralized exchange, and access to several investment vehicles. DAOs, projects, and organizations have access to asset and risk management tools like multisigs, treasuries, payroll, payments and collections.",
		"discord": "https://www.meanfi.com/",
		"image": "https://daohq-dao-images.s3.us-east-2.amazonaws.com/images/ZELKvCH-_400x400.jpg",
		"mission": "A self-custody, permissionless & trustless bank bringing crypto & DeFi to everyday banking",
		"twitter": "https://twitter.com/meanfinance",
		"website": "https://www.meanfi.com/",
		"whitepaper": "https://docs.meanfi.com/"
	},{
		"category": "[\"DeFi\"]",
		"name": "Uniswap Labs",
		"daoToken": "UNI",
		"Token address": "8FU95xFJhUUkyyCLU13HSzDLs7oC4QZdXQHL6SCeab36",
		"Treasury Address": "0x1a9C8182C09F50C8318d769245beA52c32BE35BC\n0xe3953D9d317B834592aB58AB2c7A6aD22b54075D\n0x4b4e140D1f131fdaD6fb59C13AF796fD194e4135\n0x3D30B1aB88D487B0F3061F40De76845Bec3F1e94",
		"verified": "checked",
		"chain": "[\"ETH\",\"BSC\",\"AVALANCHE\",\"TERRA\",\"SOL\"]",
		"description": "The Uniswap Protocol is the largest decentralized trading and automated market making protocol on Ethereum. The Uniswap Labs team was a major contributor to the Uniswap Protocol and now focuses on building a suite of products to support the Uniswap ecosystem. Our team is one of the most impactful in crypto. We are based out of SoHo in New York City with the option to be partially or fully remote depending on the position. \n",
		"discord": "https://discord.com/invite/FCfyBSbCU5",
		"image": "https://daohq-dao-images.s3.us-east-2.amazonaws.com/images/wG2eTAfD_400x400.jpg",
		"mission": "Protocol for trading and automated liquidity provision on ethereum",
		"twitter": "https://twitter.com/uniswap",
		"website": "https://uniswap.org/",
		"whitepaper": "https://uniswap.org/whitepaper.pdf"
	},{
		"category": "[\"DeFi\"]",
		"name": "FTX",
		"daoToken": "FTX",
		"Token address": "AGFEad2et2ZJif9jaGpdMixQqvW5i81aBdvKe7PHNfz3",
		"verified": "checked",
		"chain": "[\"BEP2\",\"ETH\",\"SOL\"]",
		"description": "FTX is a cryptocurrency exchange built by traders, for traders. FTX offers innovative products including industry-first derivatives, options, volatility products and leveraged tokens. We strive to develop a platform robust enough for professional trading firms and intuitive enough for first-time users.",
		"image": "https://daohq-dao-images.s3.us-east-2.amazonaws.com/images/wTYBW3dP_400x400.png",
		"mission": "Crypto Derivatives Exchange for traders by traders.  ",
		"twitter": "https://twitter.com/FTX_Official",
		"website": "https://ftx.com/",
		"whitepaper": "https://docs.google.com/document/d/11GAgoD06BH6rvGBlNSUwNGLlauVTvOB_vb97OS4vCio/edit"
	},{
		"category": "[\"Tooling\"]",
		"name": "0x",
		"daoToken": "ZRX",
		"Token address": "GJa1VeEYLTRoHbaeqcxfzHmjGCGtZGF3CUqxv9znZZAY",
		"Treasury Address": "0x0bB1810061C2f5b2088054eE184E6C79e1591101",
		"verified": "checked",
		"chain": "[\"ETH\",\"AVALANCHE\",\"SOL\",\"XDAI\"]",
		"description": "The 0x (zero x) protocol is a protocol that enables the peer-to-peer exchange of assets on the Ethereum blockchain. The 0x protocol was launched in 2017 by 0x Labs, an organization based in San Francisco focused on creating new markets in the 0x ecosystem.\n\nThe protocol itself is not, by definition, a decentralized exchange; it allows for the creation of decentralized exchanges that can be used in broad applications.",
		"discord": "https://discord.gg/d3FTX3M",
		"image": "https://daohq-dao-images.s3.us-east-2.amazonaws.com/images/sHGUQ_0F_400x400.jpg",
		"mission": "Decentralized exchange infrastructure for the internet",
		"twitter": "https://twitter.com/0xProject",
		"website": "https://0x.org/",
		"whitepaper": "https://whitepaper.io/document/20/0x-whitepaper"
	},{
		"category": "[\"DeFi\"]",
		"name": "Curve Finance",
		"daoToken": "CRV",
		"Token address": "7gjNiPun3AzEazTZoFEjZgcBMeuaXdpjHq2raZTmTrfs",
		"Treasury Address": "0xe3997288987E6297Ad550A69B31439504F513267",
		"verified": "checked",
		"chain": "[\"XDAI\",\"ETH\",\"SOL\",\"FANTOM\"]",
		"description": "Curve Finance is a decentralized exchange (DEX) running on Ethereum. It's specifically designed for swapping between stablecoins. All you need is an Ethereum wallet, some funds, and you can swap different stablecoins with low fees and slippage.\n\nYou could think of Curve as \"Uniswap for stablecoins.\" Thanks to its special pricing formula, it's also great for swapping between different tokenized versions of a coin.",
		"discord": "https://discord.gg/9uEHakc",
		"image": "https://daohq-dao-images.s3.us-east-2.amazonaws.com/images/W1sQNVWo_400x400.jpg",
		"mission": "Creating deep on-chain liquidity using advanced bonding curves",
		"twitter": "https://twitter.com/CurveFinance",
		"website": "https://curve.fi/",
		"whitepaper": "https://resources.curve.fi/"
	},{
		"category": "[\"DeFi\"]",
		"name": "Serum",
		"daoToken": "SRM",
		"Token address": "SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt",
		"Treasury Address": "7jt7Hw1iypXN3otudBeTPkY2K4yotWMTegWeAxnt1h3c",
		"verified": "checked",
		"chain": "[\"ETH\",\"SOL\",\"BSC\",\"TERRA\"]",
		"description": "Serum is a protocol and ecosystem that brings unprecedented speed and low transaction costs to decentralized finance. It is built on Solana and is completely permissionless. Ecosystem partners can compose with Serum’s on-chain central limit orderbook to share liquidity and power markets-based features for institutional and retail users.\n\nMore specifically, Serum's on-chain central limit order book and matching engine provides liquidity and price-time-priority matching to traders and composing projects. Users benefit from this exchange model through the ability to choose the price, size and direction of their trades. Composing projects benefit from Serum’s existing architecture, bootstrapped liquidity, and matching service.",
		"discord": "https://discord.com/invite/wZbHams7KV/",
		"image": "https://daohq-dao-images.s3.us-east-2.amazonaws.com/images/aN4Pq1iS_400x400.jpg",
		"mission": "Serum brings the speed and convenience of centralized exchanges to DeFi while remaining fully trustless and transparent",
		"twitter": "https://twitter.com/ProjectSerum",
		"website": "https://linktr.ee/projectserum",
		"whitepaper": "https://whitepaper.io/document/626/serum-whitepaper"
	},{
		"category": "[\"Gaming\"]",
		"name": "Illuvinati Governance",
		"daoToken": "ILV",
		"Token address": "8UJbtpsEubDVkY53rk7d61hNYKkvouicczB2XmuwiG4g",
		"verified": "checked",
		"chain": "[\"ETH\",\"SOL\"]",
		"description": "You take the role of a survivor of a transport vessel in an intergalactic space fleet, investigating a perplexing distress beacon. When you finally reach the origin of the call, you discover a ruined planet, possibly the mythical cradle of your race’s civilization. A vast crystal ocean engulfs all but a tiny fraction of the planet. Extreme weather events assault the surface, giving way to strikingly varied climates. A burst of radiation disables the ship’s engines and you slam into the planet’s surface. Crawling free from the wreckage, you discover majestic beasts, some with near godlike power. Could this be what caused the downfall of this planet? Luckily, your race has begun to master the same energy that the Illuvials harness, and you are able to capture and control the deity-like fauna into slivers of crystal called Shards, mined from the planet’s surface. To uncover the mysteries of the planet, you become a Hunter, traveling across the land subduing and capturing Illuvials, and trying to unlock the Obelisks that keep most of the world closed off.",
		"discord": "https://discord.com/invite/illuvium",
		"image": "https://daohq-dao-images.s3.us-east-2.amazonaws.com/images/8NVkjxmn_400x400.jpg",
		"mission": "Illuvium is an open-world fantasy battle game built on the Ethereum blockchain. Often touted as the first AAA game on Ethereum, Illuvium looks to provide a source of entertainment to both casual gamers and hardcore DeFi fans through a range of collecting and trading features.",
		"twitter": "https://twitter.com/illuviumio",
		"website": "https://www.illuvium.io/",
		"whitepaper": "https://docs.illuvium.io/"
	},{
		"category": "[\"Gaming\"]",
		"name": "Aurory",
		"daoToken": "AURY",
		"Token address": "AURYydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP",
		"verified": "checked",
		"chain": "[\"SOL\",\"BSC\"]",
		"description": "You take the role of a survivor of a transport vessel in an intergalactic space fleet, investigating a perplexing distress beacon. When you finally reach the origin of the call, you discover a ruined planet, possibly the mythical cradle of your race’s civilization. A vast crystal ocean engulfs all but a tiny fraction of the planet. Extreme weather events assault the surface, giving way to strikingly varied climates. A burst of radiation disables the ship’s engines and you slam into the planet’s surface. Crawling free from the wreckage, you discover majestic beasts, some with near godlike power. Could this be what caused the downfall of this planet? Luckily, your race has begun to master the same energy that the Illuvials harness, and you are able to capture and control the deity-like fauna into slivers of crystal called Shards, mined from the planet’s surface. To uncover the mysteries of the planet, you become a Hunter, traveling across the land subduing and capturing Illuvials, and trying to unlock the Obelisks that keep most of the world closed off.",
		"discord": "https://discord.gg/aurory",
		"image": "https://daohq-dao-images.s3.us-east-2.amazonaws.com/images/Z7-vVlC-_400x400.jpg",
		"mission": "Gaming platform based on the play-to-earn mechanism",
		"twitter": "https://twitter.com/AuroryProject",
		"website": "https://aurory.io/",
		"whitepaper": "https://aurory.io/whitepaper.html"
	},{
		"category": "[\"Gaming\"]",
		"name": "DeFiLand",
		"daoToken": "DFL",
		"Token address": "DFL1zNkaGPWm1BqAVqRjCZvHmwTFrEaJtbzJWgseoNJh",
		"verified": "checked",
		"chain": "[\"SOL\"]",
		"description": "DeFi Land is a multi-chain agriculture-simulation game created to gamify Decentralized Finance. Our game will have all the features that traditional platforms have but it will be gathered all in one place. Players will be able to start playing the game for free, grind their way up to the play-2-earn tier, compete with others, craft, trade and more.",
		"discord": "https://discord.gg/defiland",
		"image": "https://daohq-dao-images.s3.us-east-2.amazonaws.com/images/5SP1ZtJP_400x400.jpg",
		"mission": "Multi-chain agriculture simulation web-game created to gamify decentralized finance",
		"twitter": "https://twitter.com/DeFi_Land",
		"website": "https://defiland.app/",
		"whitepaper": "https://docs.defiland.app/"
	},{
		"category": "[\"DeFi\",\"Investment\"]",
		"name": "Magic Internet 🧙🏼‍♂️",
		"daoToken": "SPELL",
		"Token address": "BCsFXYm81iqXyYmrLKgAp3AePcgLHnirb8FjTs6sjM7U",
		"verified": "checked",
		"chain": "[\"ETH\",\"POLYGON\",\"FANTOM\",\"AVALANCHE\",\"SOL\",\"TERRA\"]",
		"description": "Abracadabra.money is a lending platform that uses interest-bearing tokens (ibTKNs) as collateral to borrow a USD pegged stablecoin (Magic Internet Money - MIM), that can be used as any other traditional stablecoin.\n",
		"discord": "https://discord.com/invite/wcsUNxYrFM",
		"image": "https://daohq-dao-images.s3.us-east-2.amazonaws.com/images/YmUl6Gdn_400x400.jpg",
		"mission": "A spell book that allows users to produce magic internet money ($MIM) -- a stable coin that users can swap for any other traditional stable coin",
		"twitter": "https://twitter.com/mim_spell",
		"website": "https://abracadabra.money/",
		"whitepaper": "https://docs.abracadabra.money/"
	}
]